# Generated by Django 5.2.1 on 2025-06-10 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='servicios',
            field=models.ManyToManyField(blank=True, related_name='empleados', to='core.servicio', verbose_name='servicios asignados'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.sucursal', verbose_name='sucursal'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='ventanilla_asignada',
            field=models.CharField(max_length=10, verbose_name='ventanilla asignada'),
        ),
    ]
