# Generated by Django 5.2.3 on 2025-08-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0005_fix_servicio_sucursal_relation'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            ALTER TABLE empleados_servicios 
            ADD COLUMN IF NOT EXISTS fecha_asignacion timestamp with time zone NOT NULL DEFAULT NOW();
            ALTER TABLE empleados_servicios 
            ADD COLUMN IF NOT EXISTS activo boolean NOT NULL DEFAULT true;
            """,
            reverse_sql="""
            ALTER TABLE empleados_servicios DROP COLUMN IF EXISTS fecha_asignacion;
            ALTER TABLE empleados_servicios DROP COLUMN IF EXISTS activo;
            """
        )
    ]
