# Generated by Django 5.2.3 on 2025-06-27 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_empleado_servicios_alter_empleado_sucursal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioSinStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True, verbose_name='cédula')),
                ('telefono', models.CharField(max_length=15, verbose_name='teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='correo electrónico')),
            ],
            options={
                'verbose_name': 'usuario sin staff',
                'verbose_name_plural': 'usuarios sin staff',
                'db_table': 'usuarios_sin_staff',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='empleado',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.sucursal', verbose_name='sucursal'),
        )
    ]
