# Generated by Django 5.2.3 on 2025-08-10 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_servicio_sucursal_relation'),
        ('users', '0002_fix_empleados_servicios_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioSinStaff',
        ),
        migrations.AlterModelOptions(
            name='empleadoservicio',
            options={'verbose_name': 'servicio de empleado', 'verbose_name_plural': 'servicios de empleado'},
        ),
        migrations.RemoveField(
            model_name='empleadoservicio',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='empleadoservicio',
            name='fecha_asignacion',
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado'),
        ),
        migrations.AlterField(
            model_name='empleadoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio'),
        ),
    ]
