# Generated by Django 5.2.1 on 2025-06-05 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_sucursal', models.CharField(max_length=20, unique=True, verbose_name='Código Sucursal')),
                ('direccion', models.TextField(verbose_name='Dirección')),
                ('telefono', models.CharField(blank=True, max_length=15, null=True, verbose_name='Teléfono')),
                ('ciudad', models.CharField(max_length=50, verbose_name='Ciudad')),
                ('departamento', models.CharField(max_length=50, verbose_name='Departamento')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('configuracion', models.JSONField(default=dict, verbose_name='Configuración')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursales',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('codigo_servicio', models.CharField(max_length=20, verbose_name='Código Servicio')),
                ('tiempo_estimado_atencion', models.PositiveIntegerField(default=15, verbose_name='Tiempo Estimado (min)')),
                ('color_identificacion', models.CharField(blank=True, max_length=7, null=True, verbose_name='Color')),
                ('icono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ícono')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='clave')),
                ('valor', models.JSONField(default=dict, verbose_name='valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('categoria', models.CharField(default='general', max_length=50, verbose_name='categoría')),
                ('es_global', models.BooleanField(default=True, verbose_name='es global')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_sucursal', to='core.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuraciones',
                'db_table': 'configuraciones',
                'unique_together': {('clave', 'sucursal')},
            },
        ),
    ]
