# Generated by Django 5.2.1 on 2025-06-02 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=100, unique=True, verbose_name='clave')),
                ('valor', models.JSONField(default=dict, verbose_name='valor')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='descripción')),
                ('categoria', models.CharField(default='general', max_length=50, verbose_name='categoría')),
                ('es_global', models.BooleanField(default=True, verbose_name='es global')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='fecha de actualización')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_sucursal', to='core.sucursal', verbose_name='sucursal')),
            ],
            options={
                'verbose_name': 'configuración',
                'verbose_name_plural': 'configuraciones',
                'db_table': 'configuraciones',
                'unique_together': {('clave', 'sucursal')},
            },
        ),
    ]
