# Generated by Django 4.2.7 on 2025-07-24 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='color_identificacion',
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='icono',
        ),
        migrations.RemoveField(
            model_name='sucursal',
            name='configuracion',
        ),
    ]
