# Generated by Django 4.2.7 on 2025-07-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_servicio_color_identificacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiasSemana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'verbose_name': 'dia de la semana',
                'verbose_name_plural': 'dias de la semana',
                'db_table': 'dias_semana',
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='descripcion',
            field=models.CharField(default='Sin descripción', max_length=255),
        ),
    ]
