# Generated by Django 5.2.1 on 2025-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_configuracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
