# Generated by Django 4.2.7 on 2025-07-24 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_diassemana_sucursal_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diassemana', verbose_name='Día de la semana')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Dia Sucursal',
                'verbose_name_plural': 'Dia Sucursales',
                'db_table': 'dia_sucursales',
                'unique_together': {('sucursal', 'dia_semana')},
            },
        ),
    ]
