# Generated by Django 5.2.3 on 2025-08-06 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diasucursal'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE servicios ADD COLUMN IF NOT EXISTS sucursal_id integer REFERENCES sucursales(id);",
            reverse_sql="ALTER TABLE servicios DROP COLUMN IF EXISTS sucursal_id;"
        ),
        migrations.RunSQL(
            sql="""
            CREATE TABLE IF NOT EXISTS empleados_servicios (
                id SERIAL PRIMARY KEY,
                empleado_id integer NOT NULL REFERENCES users_empleado(id),
                servicio_id integer NOT NULL REFERENCES servicios(id),
                fecha_asignacion timestamp with time zone NOT NULL,
                activo boolean NOT NULL,
                UNIQUE(empleado_id, servicio_id)
            );
            """,
            reverse_sql="DROP TABLE IF EXISTS empleados_servicios;"
        )
    ]
