# Generated by Django 4.2.7 on 2025-08-12 21:26

from django.db import migrations, models
import django.db.models.deletion

def seed_dias(apps, schema_editor):
    DiaSemana = apps.get_model('core', 'DiasSemana')
    dias = ["Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado", "Domingo"]
    for dia in dias:
        DiaSemana.objects.get_or_create(nombre=dia)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_diasucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_apertura', models.TimeField(verbose_name='Hora de apertura')),
                ('hora_cierre', models.TimeField(verbose_name='Hora de cierre')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('dia_semana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.diassemana', verbose_name='Día de la semana')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='Sucursal')),
            ],
            options={
                'verbose_name': 'Horario Sucursal',
                'verbose_name_plural': 'Horarios Sucursales',
                'db_table': 'horario_sucursales',
            },
        ),
        migrations.DeleteModel(
            name='DiaSucursal',
        ),
    ]
