# Generated by Django 4.2.7 on 2025-08-12 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_horariosucursal_delete_diasucursal'),
        ('core', '0006_auto_seed_dias'),
    ]

    operations = [
    ]
