# Generated by Django 4.2.7 on 2025-08-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_servicio_sucursal_relation'),
        ('core', '0007_merge_20250812_1722'),
    ]

    operations = [
    ]
