# Generated by Django 4.2.7 on 2025-05-27 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_turno', models.CharField(max_length=20, verbose_name='número de turno')),
                ('estado', models.CharField(choices=[('en_espera', 'En espera'), ('llamado', 'Llamado'), ('en_atencion', 'En atención'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado'), ('ausente', 'Ausente'), ('transferido', 'Transferido')], default='en_espera', max_length=20, verbose_name='estado')),
                ('prioridad', models.IntegerField(default=0, verbose_name='prioridad')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_llamado', models.DateTimeField(blank=True, null=True, verbose_name='fecha de llamado')),
                ('fecha_inicio_atencion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio de atención')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización')),
                ('tiempo_espera_estimado', models.IntegerField(blank=True, null=True, verbose_name='tiempo de espera estimado (min)')),
                ('es_agendado', models.BooleanField(default=False, verbose_name='es agendado')),
                ('fecha_agendada', models.DateTimeField(blank=True, null=True, verbose_name='fecha agendada')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado', verbose_name='empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'db_table': 'turnos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('llamado_turno', 'Llamado de turno'), ('turno_finalizado', 'Turno finalizado'), ('turno_cancelado', 'Turno cancelado'), ('turno_transferido', 'Turno transferido'), ('sistema', 'Sistema')], max_length=30, verbose_name='tipo')),
                ('titulo', models.CharField(max_length=100, verbose_name='título')),
                ('mensaje', models.TextField(verbose_name='mensaje')),
                ('leida', models.BooleanField(default=False, verbose_name='leída')),
                ('fecha_envio', models.DateTimeField(auto_now_add=True, verbose_name='fecha de envío')),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True, verbose_name='fecha de lectura')),
                ('canal', models.CharField(choices=[('websocket', 'WebSocket'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='websocket', max_length=20, verbose_name='canal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'notificación',
                'verbose_name_plural': 'notificaciones',
                'db_table': 'notificaciones',
                'ordering': ['-fecha_envio'],
            },
        ),
        migrations.CreateModel(
            name='ColaTurnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion_cola', models.IntegerField(verbose_name='posición en cola')),
                ('fecha_ingreso_cola', models.DateTimeField(auto_now_add=True, verbose_name='fecha de ingreso a cola')),
                ('tiempo_espera_estimado', models.IntegerField(blank=True, null=True, verbose_name='tiempo de espera estimado (min)')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'cola de turnos',
                'verbose_name_plural': 'colas de turnos',
                'db_table': 'cola_turnos',
                'ordering': ['posicion_cola'],
            },
        ),
        migrations.CreateModel(
            name='CalificacionServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(verbose_name='calificación')),
                ('comentario', models.TextField(blank=True, null=True, verbose_name='comentario')),
                ('aspectos_evaluados', models.JSONField(blank=True, default=dict, verbose_name='aspectos evaluados')),
                ('fecha_calificacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de calificación')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado', verbose_name='empleado')),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio')),
                ('turno', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'calificación de servicio',
                'verbose_name_plural': 'calificaciones de servicio',
                'db_table': 'calificaciones_servicio',
                'ordering': ['-fecha_calificacion'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('turnos_atendidos', models.IntegerField(default=0, verbose_name='turnos atendidos')),
                ('tiempo_promedio_atencion', models.IntegerField(default=0, verbose_name='tiempo promedio de atención (min)')),
                ('calificacion_promedio', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='calificación promedio')),
                ('tiempo_conectado', models.IntegerField(default=0, verbose_name='tiempo conectado (min)')),
                ('turnos_transferidos', models.IntegerField(default=0, verbose_name='turnos transferidos')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='creado el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='actualizado el')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'estadística de empleado',
                'verbose_name_plural': 'estadísticas de empleados',
                'db_table': 'estadisticas_empleado',
                'ordering': ['-fecha'],
                'unique_together': {('empleado', 'fecha')},
            },
        ),
    ]
