# Generated by Django 4.2.7 on 2025-07-24 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('turns', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to='users.empleado', verbose_name='empleado'),
        ),
        migrations.AddField(
            model_name='turno',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='turno',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='sucursal'),
        ),
        migrations.AddField(
            model_name='turno',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='turno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddField(
            model_name='estadisticaempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='empleado'),
        ),
        migrations.AddField(
            model_name='colaturnos',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='colaturnos',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno'),
        ),
        migrations.AddField(
            model_name='calificacionservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado', verbose_name='empleado'),
        ),
        migrations.AddField(
            model_name='calificacionservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicio', verbose_name='servicio'),
        ),
        migrations.AddField(
            model_name='calificacionservicio',
            name='turno',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='turns.turno', verbose_name='turno'),
        ),
        migrations.AddField(
            model_name='calificacionservicio',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AlterUniqueTogether(
            name='estadisticaempleado',
            unique_together={('empleado', 'fecha')},
        ),
    ]
