# Generated by Django 5.2.1 on 2025-06-05 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacionservicio',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.empleado', verbose_name='empleado'),
        ),
        migrations.AlterField(
            model_name='estadisticaempleado',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.empleado', verbose_name='empleado'),
        ),
        migrations.DeleteModel(
            name='Empleado',
        ),
    ]
