# Generated by Django 4.2.7 on 2025-07-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='empleado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='es_agendado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_agendada',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_finalizacion',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_inicio_atencion',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='fecha_llamado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='tiempo_espera_estimado',
        ),
        migrations.RemoveField(
            model_name='turno',
            name='usuario',
        ),
        migrations.AddField(
            model_name='turno',
            name='nombre_cliente',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='nombre del cliente'),
        ),
        migrations.AddField(
            model_name='turno',
            name='numero_cedula',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='número de cédula'),
        ),
    ]
