# Generated by Django 4.2.7 on 2025-07-25 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0003_remove_turno_empleado_remove_turno_es_agendado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='fecha_finalizacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de finalización'),
        ),
        migrations.AddField(
            model_name='turno',
            name='fecha_inicio_atencion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de inicio de atención'),
        ),
    ]
