# Generated by Django 4.2.7 on 2025-06-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0003_check_column_type'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.AddField(
                    model_name='turno',
                    name='prioridad',
                    field=models.IntegerField(default=0, help_text='Prioridad del turno (mayor número = mayor prioridad)', verbose_name='prioridad'),
                ),
            ]
        ),
    ]
