# Generated by Django 5.2.3 on 2025-07-31 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0004_turno_fecha_finalizacion_turno_fecha_inicio_atencion'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_atendidos', to='users.empleado'),
        ),
    ]
