# Generated by Django 5.2.3 on 2025-06-27 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turns', '0004_turno_prioridad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='prioridad',
        ),
    ]
