# Generated by Django 5.2.3 on 2025-08-09 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fix_servicio_sucursal_relation'),
        ('turns', '0005_turno_empleado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacionservicio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.sucursal', verbose_name='sucursal'),
        ),
    ]
