from .roles_serializer import UsuarioSerializer, EmpleadoSerializer, AdministradorSerializer
from .registro_usuario_serializer import RegistroUsuarioSerializer
from .registro_empleado_serializer import RegistroEmpleadoSerializer
from .inicio_sesion_serializer import InicioSesionSerializer
from .inicio_sesion_admin_serializer import InicioSesionAdminSerializer
from .empleado_login_serializer import EmpleadoLoginSerializer